### ISSUE TITLE
修改一些链接地址错误！

### ISSUE THREAD

**Issue by zhisheng17** [xitu/awesome-kotlin-cn#1]
Kotlin 官网    [http://kotlinlang.org/](http://kotlinlang.org/)
Kotlin 文档    [http://www.kotlincn.net/docs/reference/](http://www.kotlincn.net/docs/reference/)

**Comment by yikejiucai** [comment]
## 官网及文档

- [Kotlin 官网](https://kotlinlang.org/)
- [Kotlin 文档](https://kotlinlang.org/docs/reference/)
- [Kotlin 文档中文版](http://www.kotlincn.net/docs/reference/)
- [Kotlin on GitHub](https://github.com/JetBrains/kotlin)

没看到哪里错了啊..

**Comment by zhisheng17** [comment]
不好意思，之前那天在我电脑上打开 https 的 Kotlin 官网进不去，发生错误，只有 http 的才能访问，现在好了。
